### ISSUE TITLE
Incorrect call to dnf for RHEL/Centos 7 in postgresql12_install.yml

### ISSUE THREAD

**Issue by alexscottthatcham** [ansible-lockdown/POSTGRES-12-CIS#6]
- name: "PRELIM | Install and Start PostgreSQL | Disable built in PostgreSQL RHEL/CentOS 7"
        shell: dnf -y module disable postgresql
        register: prelim_disable_pgs_old_rh8
        changed_when: "'Disabling modules' in prelim_disable_pgs_old_rh8.stdout"
        when: ansible_distribution_major_version == "7"

Shell should be yum not dnf?
Register/changed_when should be prelim_disable_pgs_old_rh7, not prelim_disable_pgs_old_rh8?

**Comment by georgenalen** [comment]
Closed with PR #7
